name: Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  integration-job:
    runs-on: arc-runner-set-order
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    env:
      DOTNET_INSTALL_DIR: "/usr/lib/dotnet"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore tools
        run: |
          dotnet tool restore

      - name: Verify NuGet Packages
        run: |
          dotnet restore 
          dotnet list package --outdated
        continue-on-error: true

      - name: Lint sources
        run: |
          dotnet format --verify-no-changes

      - name: Run tests
        run: |
          dotnet test